export { default as Header} from './components/Header';
export { default as Footer} from './components/Footer';
export { default as Sidebar} from './components/Sidebar';
export { default as Dashboard } from './pages/Dashboard';
export { default as AddPatient } from './pages/AddPatient';
export { default as PatientList } from './pages/PatientList';
export { default as AddDoctorSchedule } from './pages/AddDoctorSchedule';
export { default as DoctorScheduleList } from './pages/DoctorScheduleList';
export { default as AddAppointment } from './pages/AddAppointment';
export { default as AppointmentList } from './pages/AppointmentList';
export { default as AddDiagnoses } from './pages/AddDiagnoses';
export { default as DiagnosesList } from './pages/DiagnosesList';
export { default as DashboardLayouts } from './components/DashboardLayouts';
export { default as UserLogin } from './auth/UserLogin';
export { default as PatientLogin } from './auth/PatientLogin';
export { default as PatientRegister } from './auth/PatientRegister';
export { default as UserList } from './pages/UserList';
export { default as AddUser } from './pages/AddUser';