export { default as Header} from './components/Header';
export { default as Footer} from './components/Footer';
export { default as Sidebar} from './components/Sidebar';
export { default as Dashboard } from './pages/Dashboard';
export { default as AddDoctor } from './pages/AddDoctor';
export { default as DoctorList } from './pages/DoctorList';
export { default as AddPatient } from './pages/AddPatient';
export { default as PatientList } from './pages/PatientList';
export { default as AddDoctorSchedule } from './pages/AddDoctorSchedule';
export { default as DoctorScheduleList } from './pages/DoctorScheduleList';
export { default as AddAppointment } from './pages/AddAppointment';
export { default as AppointmentList } from './pages/AppointmentList';
export { default as AddDiagnoses } from './pages/AddDiagnoses';
export { default as DiagnosesList } from './pages/DiagnosesList';