export { default as Header} from './components/Header';
export { default as Footer} from './components/Footer';
export { default as Sidebar} from './components/Sidebar';
export { default as Dashboard } from './pages/Dashboard';
export { default as AddDoctor } from './pages/AddDoctor';
export { default as DoctorList } from './pages/DoctorList';
export { default as AddPatient } from './pages/AddPatient';
export { default as PatientList } from './pages/PatientList';
export { default as AddDoctorSchedule } from './pages/AddDoctorSchedule';
export { default as DoctorScheduleList } from './pages/DoctorScheduleList';
export { default as AddAppointment } from './pages/AddAppointment';
export { default as AppointmentList } from './pages/AppointmentList';
export { default as AddDiagnoses } from './pages/AddDiagnoses';
export { default as DiagnosesList } from './pages/DiagnosesList';
export { default as Home } from './pages/Home';
export { default as HomeHeader } from './components/HomeHeader';
export { default as DashboardLayouts } from './components/DashboardLayouts';
export { default as HospitalLogin } from './auth/hospital/HospitalLogin';
export { default as HospitalRegister } from './auth/hospital/HospitalRegister';
export { default as DoctorLogin } from './auth/doctor/DoctorLogin';
export { default as DoctorRegister } from './auth/doctor/DoctorRegister';
export { default as PatientLogin } from './auth/patient/PatientLogin';
export { default as PatientRegister } from './auth/patient/PatientRegister';
export { default as Navbar } from './components/Navbar';
export { default as Services } from './components/Services';
export { default as About } from './components/About';